### ISSUE TITLE
Developing find-average.js script

### ISSUE THREAD

**Issue by fmkarakus** [fmkarakus/array-of-numbers#9]
On this step user can display the average of the numbers in the array by pressing `find the average of all numbers` button.
The function finds the average of all the numbers in the array and displays the result.

Steps:

- [ ] The new repo branch  was generated

- [ ] The core logic function was developed

- [ ] It was passed through a set of tests

- [ ] PR was raised, reviewed by two assigned reviewers and the branch was merged to the master branch.

**Comment by HazemBittar** [comment]
I wrote the formula for this function...
